baseURL = "/blog"
languageCode = "en-us"
title = "Alejandro AO - Coding Knowledge Base"
theme = "cactus"
defaultContentLanguage = "en"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[params]
colortheme = "dark"
showAllPostsOnHomePage = false
postsOnHomePage = 10
showProjectsList = true
projectsUrl = "https://github.com/aavila0707"
showAllPostsArchive = true

[[params.social]]
name = "github"
link = "https://github.com/aavila0707"

[[params.social]]
name = "linkedin"
link = "https://linkedin.com/in/aavila0707"

[[params.social]]
name = "email"
link = "alejandro@progressifmedia.com"

[params.comments]
enabled = true
enigne = "disqus"

[markup.highlight]
codeFences = true
guessSyntax = false
hl_Lines = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = "monokai"
tabWidth = 4
