# baseURL = "/blog"  # prod
# baseURL = "https://alejandro-ao.github.io/" # prod on aavila0707.github.io
baseURL = "https://codeinfrance.com/" # prod on codeinfrance.com
languageCode = "en-us"
title = "Code in France - Full Stack Developer in France 🇫🇷"
theme = "cactus"
defaultContentLanguage = "en"
googleAnalytics = 'G-1B1DSVJ5J0'

[params.comments]
enabled = true
enigne = "disqus"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "Categories"
url = "/categories"
weight = 3

[[menu.main]]
name = "About"
url = "/about"
weight = 4

[params]
colortheme = "white" # dark, light, white, or classic
showAllPostsOnHomePage = false
postsOnHomePage = 20
showProjectsList = false
# projectsUrl = "https://github.com/aavila0707"
showAllPostsArchive = true
logo = "/images/logo.png"
css = ["css/custom.css"]

[[params.social]]
name = "github"
link = "https://github.com/aavila0707"

[[params.social]]
name = "linkedin"
link = "https://linkedin.com/in/aavila0707"

[[params.social]]
name = "email"
link = "alejandro@progressifmedia.com"


[markup.highlight]
codeFences = true
guessSyntax = false
hl_Lines = ""
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
style = "monokai"
tabWidth = 4
